### ISSUE TITLE
give more guidance around how to add oneself to the site

### ISSUE THREAD

**Issue by afeld** [18F/18f.gsa.gov#1116]
The first step of [the instructions](https://github.com/18F/18f.gsa.gov/#adding-yourself-to-the-site) (adding the YAML file) is a bit vague...maybe we can create a template for the YAML or something that people can copy-and-paste into the GitHub editing interface. Might make sense for that part of the instructions to live in https://github.com/18F/data-private.

I nominate Esther (Kim) and @annahsebok to be the guinea pigs for testing that the instructions can be followed without GitHub experience :wink: 

/cc @mbland

**Comment by gboone** [comment]
Good idea, @afeld. I'm 99% sure adding and checking the YAML file is completely unnecessary. We use the information there to name and fill in some detail on the `_team/` markdown file for each person but we don't depend on it. Maybe we move that out to a bullet point in the helpful tips section.

**Comment by afeld** [comment]
I think it's useful to have people fill it out – we should just give more explicit easy-to-follow steps. Will take a crack at it soon.

**Comment by wslack** [comment]
I have the step by step for that in the Github course sheet. https://docs.google.com/document/d/18b-4VPTcuqat-enGQSVzivGH2CsqdQVG0K0eToRM39I/edit#bookmark=id.d1moj646jvtu cc @afeld

**Comment by elainekamlley** [comment]
+1 to removing the first step. Thats on our team to make sure its there since we are the ones creating the `.md` file. Also, I've been behind in adding the bios (my bad!) but lets put some accountability measure and add timeframe: "New bios will be added the last week of each month" 

We also then can add instructions on how to update with step by step instructions on PR or pinging the team with updated text.

**Comment by elainekamlley** [comment]
Updated the README to include simplified instructions. Take a look @afeld and @annahsebok, let me know what you think. :smile:

**Comment by afeld** [comment]
:+1:
