### ISSUE TITLE
Add 18F GitHub issues widget via CfAPI

### ISSUE THREAD

**Issue by maya** [18F/18f.gsa.gov#1186]
We should include issues to 18F projects for outside people to easily view and contribute to.

CfAPI already aggregates this for us. This is a link to all 18F issues with the tag "help wanted" (showing 12):

https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=18F&labels=help%20wanted&number=12

Here is the code for embedding:

`<iframe src="https://www.codeforamerica.org/geeks/civicissues/widget?organization_name=18F&labels=help wanted&number=12" width="100%" height="600" frameBorder="0"></iframe>`

I don't know where on the site it could go, but we can talk about it!

This is what it looks like:

![kaaqiecbagqiaaaqiecbagqiaaaqiecbagqiaaaqiecbagqiaaaqiebgfx1obqkgabagqiecbagaabagqiecbagaabagqiecbagaabagqiecbagaabauishybagaabagqiecbagaabagqiecbagaabagqiecbagaabagqiecbagmagim4aue0siecaaaecbagqiecaaaecbagqiecaaaecbagqiecaaaecbagqiebanoudbagqiecaaaec](https://cloud.githubusercontent.com/assets/5249443/9974068/88e36e46-5e35-11e5-9dd9-d281d11bf922.png)

**Comment by gboone** [comment]
We've thought about putting integrating this before, but on the site and the dashboard and we're also talking about building out a more robust contribute-to-18F projects experience on 18f.gsa.gov. @jenniferthibault curious where you think this might fit into those designs?

**Comment by jenniferthibault** [comment]
OH NEAT! 

Those designs are still on pause right now (because, capacity and billable projects), though with the branding work we've started up, this is a great feature to keep in mind. It will all likely overlap the website redesign. Heads up @ericronne

**Comment by hursey013** [comment]
I've been looking for some 18F issues to contribute to and stumbled upon the "help wanted" tag.  Since Github doesn't provide a great way (that I know of) to browse that tag over multiple repositories I put together a simple issue browser: http://helpwanted.bhurst.me/

It's not perfect, since the use of "help wanted" isn't totally consistent, but if the use of that tag focuses a bit more over time, it could be a good way to get some more visibility into 18F specific issues and maybe get some more contributions from the public.  It's really just a proof of concept, but I'm happy to host/maintain the site if it's something you find useful, or at the very least, hopefully it can provide some ideas for your own implementation of something similar.
