### ISSUE TITLE
Evaluate required gems in Gemfile

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#1286]
There are several gems we might not need anymore in order to run the build. `bourbon`, for example, is likely not needed for building the whole site. And `rouge` _might_ be installed as a dependency of Jekyll, making our inclusion of it redundant.

We should move as many dependencies out of the Gemfile as possible to make the stack a bit simpler. See also: https://gemnasium.com/18F/18f.gsa.gov

**Comment by afeld** [comment]
> `rouge` _might_ be installed as a dependency of Jekyll

Since it's a Jekyll dependency (you can see this in the [Gemfile.lock](https://github.com/18F/18f.gsa.gov/blob/a4269f50205d5dbbf86a78069ed8e435f58b7138/Gemfile.lock#L45) or [the RubyGems page](https://rubygems.org/gems/jekyll)), it will be installed regardless of whether you include it explicitly in the Gemfile or not.
