### ISSUE TITLE
Bring join.18f.gov content into site

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1908]
I'd like to replace https://18f.gsa.gov/join/ content with the content on join.18f.gov. Currently, 18f.gsa.gov/join basically just points to join.18f.gov, but when users get there they are presented with an entirely different design and no clear way back to 18f.gsa.gov. 

A review/update of the content on join.18f.gov would probably also be helpful. 

I believe this was mocked up in a way that preserved the join.18f.gov information architecture and used the Design Standards for the sidebar navigation. Will have to go look for that inVision file.

**Comment by coreycaitlin** [comment]
Next steps:

- [ ] Find prior mockups — @awfrancisco, any luck?
- [ ] Content inventory to identify overlap and inconsistencies — @coreycaitlin 
- [ ] Meet to talk about how the content structure and design before we migrate it — @ericronne and @coreycaitlin

**Comment by awfrancisco** [comment]
Added a step about talking to Talent. Happy to facilitate this.

**Comment by coreycaitlin** [comment]
Created issue #1954 for the design chunk of this

**Comment by coreycaitlin** [comment]
@rooneywp pointed out that it would be helpful to write a bit more about what we're trying to accomplish on the Join page. Here's my initial take:

- This page should give people the information they need to successfully send in their application to 18F (in conjunction with the PD or job posting, wherever that is)
- This page should also give people enough information about the remainder of the process that they have some reference point and understand what is normal.
- This page should be a welcoming, accessible introduction to some of the complexities of getting a job in the federal government.

We *don't* expect this page to accomplish these things:

- Telling people exactly what will happen or what order; this can change in each hiring round, and can be unpredictable from role to role
- Giving guidance about specific roles or position descriptions
- Duplicating content that can be found elsewhere

This page should be — at least — comparable to the information you can find about applying to private companies, and we fully understand and expect that applicants will have further questions to discuss with their recruiter or contact at 18F.

We should avoid content that changes frequently or is likely to become outdated, because we have limited resources for maintaining this content.

Anything else, @rooneywp @fureigh @awfrancisco ? Anything else we should look at from the old repo?

**Comment by awfrancisco** [comment]
Those all sound good. Design wise, I think it should be immediately clear whether we have open positions (and what those are) and that any questions should be directed to join18f@gsa.gov.

**Comment by awfrancisco** [comment]
Are we planning to bring in the team-specific interview content to go under `Interviewing for a specific team?`? Seems like that run into another subpage problem.

**Comment by coreycaitlin** [comment]
Team-specific interview guidance:

- I recommend that we don't try to maintain this content as part of the main joining 18F content, but send it to applicants when relevant OR include it in the content for a specific opening.

Question:

- Do people still choose their GS level before applying?
- Is there accurate information in the GS-level table that you can't find elsewhere?

Todo:

- Add title to page
- Add link styling for open positions - one link per position
- Style the "no open positions" as a clearer alert
- Build scaffolding for the open positions page/section
   - single page per job posting
   - link back to Joining 18F page

**Comment by rooneywp** [comment]
**re: Team-specific interview guidance**
I agree with having the interview information sent to the candidate once they are actually going to interview. The Qualification information is what's relevant at the time of applicant and it will be included on every posting.


**Do people still choose their GS level before applying?
Is there accurate information in the GS-level table that you can't find elsewhere?**
Yes, people still select a GS level when applying. However, each job posting now includes a breakdown of what is required to be qualified at each GS level specific to the role. What the candidate may not fully understand is how GS level relates to salary. Compensation can be found elsewhere on the site, but it might not be as clear as it was laid out in the table.

**Comment by coreycaitlin** [comment]
Next steps:

- [ ] revisit GS table info and make a decision
- [ ] refine left nav
- [ ] stub out `open-positions` folder and template for each role
- [ ] document intended process for adding roles to the section

**Comment by coreycaitlin** [comment]
@kategarklavs: see also...

- https://pages.18f.gov/joining-18f/leave-policies/
- https://github.com/18F/18f.gsa.gov/blob/dev/_join/index.md
- https://github.com/18F/joining-18f/issues

**Comment by kategarklavs** [comment]
@coreycaitlin On the topic of the GS-level table: I reviewed it this afternoon and think it's a bit lengthy to include here. My thoughts are that we could either (1) link out to this table in each PD; or (2) include, at the end of each PD, a summary of what differentiates one level from the next. Thoughts?

**Comment by kategarklavs** [comment]
@coreycaitlin OK! I created PRs for everything that needed to move to the handbook. There are a few items I was unsure about (noted in the Google doc we've been working in) — perhaps we can discuss these more and I can move this info over, if necessary.

**Comment by coreycaitlin** [comment]
For the position pages....

- [ ] need some kind of breadcrumb or link back to `join` page
- [ ] need a way to include published roles (if their expiration dates are in the future)

**Comment by coreycaitlin** [comment]
The only thing left is getting the final go-ahead here, so I'm closing this out!
