### ISSUE TITLE
Allow for accessible, same-name headers

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#1931]
Currently, the 18F site uses [redcarpet's `with_toc_data` extension](https://george-hawkins.github.io/basic-gfm-jekyll/redcarpet-extensions.html#with_toc_data)  to auto-generate header with associated IDs for linking.

So that 
```
### Some header
```
becomes
```
<h3 id="some-header">Some header</h3>
```

This is all well and good until we have multiple headers on the page with the same name and we end up with two identical IDs, a problem for accessibility.

**Comment by coreycaitlin** [comment]
Can this be closed out? It looks like one solution was [mentioned here](https://github.com/18F/18f.gsa.gov/pull/1924#pullrequestreview-4304167) but I'm not sure if that solves the problem globally.

**Comment by gboone** [comment]
That's not a global fix in that if we add another page with two headers of the same name this will reappear. But with the a11y scanning, I think it's possible this bug won't end up in production again. So maybe it's a lower priority for us because of that. 

We don't _typically_ have multiple identical headers on the same page but I can think of a few scenarios when it might happen again.
