### ISSUE TITLE
Add blog tag scanning

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1941]
Create an automated way for blog tags to be scanned before posts are published. This would help avoid:
- Common mistyping/naming of existing tags
- Creation of unnecessary tags
- Blog posts missing relevant tags

This feature would not need to be a blocker for merging a blog post, only a warning or prompt. This feature is a low priority for the blog.

**Comment by gboone** [comment]
This could potentially be added to the [jekyll frontmatter test suite](https://github.com/18f/jekyll_frontmatter_tests).

**Comment by gemfarmer** [comment]
After discussing this with @mugizico and @awfrancisco separately, I think this issue could be tackled via a combination of the [jekyll frontmatter test suite](https://github.com/18f/jekyll_frontmatter_tests) that @gboone mentioned above and the content linter that JP, Moncef, and I have been building.

There are two major things that we will want to do: 
- [ ] Create a list of "currently accepted tags" so that when someone submits a PR, we can check to make sure that their tags are on the list. 
- [ ] Using the same list and this [tag hierarchy doc](https://docs.google.com/spreadsheets/d/1LqXtrtTqY2ywiuxssXKeoCmcNoyDF6Xlm1YT_uo-2Og/edit#gid=0), we can also ensure that associated tags are not ignored.

I'm not exactly sure right now (content linter pending) where the work should be done to check these things, but I do know that addressing both of these issues should address all three concerns that Andre raised above.

**Comment by gemfarmer** [comment]
Remember to document what it does, where to go to add tags in the blogging guide and on the site.

Consider mapping to common misplaced tags such as:

```
PIF --> Presidential Innovation Fellows
```

**Comment by gemfarmer** [comment]
This is done in the [gem](https://github.com/18F/jekyll_frontmatter_tests/pull/4), but not fully reflected in this repo. The list of acceptable tags has been made, but we aren't using an updated version of the gem, so the list isn't doing anything.

**Comment by coreycaitlin** [comment]
I believe this was fixed by #2209 🌮
