### ISSUE TITLE
Bug: user-centered design tag index not showing all posts

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#1947]
The tag list shows 27 posts with the tag `user-centered design` ![user-centered-design](https://cloud.githubusercontent.com/assets/12051887/19446524/d392d430-945e-11e6-9ed2-4e82d64a2986.jpg)

But the page [only shows 1 post](https://18f.gsa.gov/tags/user-centered-design/).

**Comment by awfrancisco** [comment]
I believe this could be fixed by adding a hyphen to the one post that is tagged `user centered design` but I'll wait to do that in case anyone wants to diagnose the deeper problem.

**Comment by coreycaitlin** [comment]
One concern is whether "fixing" this for our purposes, then contributing that back to the plugin project, would impose our style choices on other users, which might not be totally appropriate.

Next steps:

- @gemfarmer to investigate further
- @awfrancisco to fix the immediate `user-centered design` situation

**Comment by gboone** [comment]
Here is the related issue I opened with the Jekyl Archives project back in the day https://github.com/jekyll/jekyll-archives/issues/43

**Comment by gemfarmer** [comment]
Ok, so I did a bit more research on this today. 

Assuming that we want to monkey patch this instead of messing with Jekyll Archives itself (probably less likely to spawn new bugs), there are two major things we need to do.

1. Update the tags on each once `Jekyll` and the `Jekyll::Archives` modules have been initialized. Because the tags index page looks for tags in each post, this effectively consolidates tags like `user-centered design` and `user centered design`. I got this to work with the following code:

```ruby
def clean_tags(tags)
  cleaned_tags = []
  tags.each do |tag|
    cleaned_tags << tag.gsub(/[^0-9A-Za-z]/, ' ').squeeze
  end
  cleaned_tags
end

Jekyll::Hooks.register :posts, :pre_render do |post|
  tags = post.data['tags'] || []
  if tags.any?
    post.data['tags'] = clean_tags(post.data['tags'])
  end
end
```

2. Update the `Jekyll:Archives` module itself before it initializes. When Jekyll archives instantiates each archive it relates a given archive page (tag page) with the posts that share its tag. We somehow need to either
 - update each post page to have proper tag names OR
 - cull the archive relations that have improper tag names and supplant its related posts into the array of posts that belong to the proper version of that tag name

There doesn't seem to be much documentation on this on stackoverflow, github, or blogs (people don't mess around with Jekyll core monkey patching I guess), so the most useful documentation has been the [Jekyll Archives rubydocs API](http://www.rubydoc.info/gems/jekyll-archives/2.0.0/Jekyll/Archives/Archive)

@mugizico
