### ISSUE TITLE
Visual design for subnav

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#1954]
The join18f content is a bit deeper than any of the content currently on the site — which means it's probably time for another level of navigation. This issue is for beginning to design a sub-navigation system.

**Comment by maya** [comment]
I know the visual designers created this as a first go: 

![join18f](https://cloud.githubusercontent.com/assets/5249443/19582140/075b85a2-96e7-11e6-9d4b-3f34b2387316.jpg)

**Comment by coreycaitlin** [comment]
We'll also want to use this for intake content, including the partnership playbook.

**Comment by ericronne** [comment]
Here's a simple design for this side nav. I've separated the buttons with vertical space, rather than dividing line rules. This makes for a cleaner layout, and fits better with the rest of the site design. I also applied the thick bright blue bar as a hover state. It didn't feel right to apply the bar vertically here and horizontally along the top nav, plus this feels kind of fun to me.

## Style summary

### Default
- Regular weight, 14px / 21 + 18 after, #5b616b gray

### Hover
- Default styling, but #000000 fill
- Add 5px bar "underscore," #00cfff blue
- Note: hover has no effect on "you are here" style

### "You are here"
- Bold weight, #000000

![hire](https://cloud.githubusercontent.com/assets/9259185/19871909/18ccff68-9f85-11e6-8832-58227771365e.png)

**Comment by ericronne** [comment]
And here's how it grids out. This could change; it introduces an additional structure to our scheme. We can chat on that whenevs.

![image](https://cloud.githubusercontent.com/assets/9259185/19871989/8d49d3de-9f85-11e6-8bbc-d080420d411a.png)

**Comment by coreycaitlin** [comment]
I like this! What are your feelings about sub-pages and how we could handle that? I don't strictly know if we need them yet, but I've never met a pile of content that didn't wind up trying to sub-sub-navigate itself eventually.

**Comment by ericronne** [comment]
The design could support something like that, e.g. with something like this …

![image](https://cloud.githubusercontent.com/assets/9259185/19901744/2978dc86-a036-11e6-957b-932ade1da293.png)


Perhaps we call the basic one-level design an MVP and implement? :)

**Comment by ericronne** [comment]
@coreycaitlin ;)

**Comment by coreycaitlin** [comment]
Yes — we'll deal with the 2nd-level nav when we absolutely have to. We'll pull implementation into the next sprint or two!

**Comment by gemfarmer** [comment]
@ericronne is there a plan for the nav in mobile?

**Comment by ericronne** [comment]
@gemfarmer not designed!
@coreycaitlin should we (i) make this a priority?

**Comment by coreycaitlin** [comment]
@ericronne Ah! Yes, please — that is a good idea. Reopening 🎉

**Comment by ericronne** [comment]
Good catch, @gemfarmer. Will pick this up tomorrow.
