### ISSUE TITLE
Markdown isn't always making quotes smarter

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2007]
## Expected Behavior

When there are quotation marks or apostrophes in markdown files, they should be converted to typographically correct smart quotes for display on the site.

## Actual Behavior

I think — at least in some types of pages — this isn't quite happening. I manually corrected the smart quotes for #2006, but hypothetically that shouldn't be necessary.

## Steps to reproduce the behavior
- [ ] Make a page with straight quotes
- [ ] See if it builds in a way that corrects the quotes

**Comment by konklone** [comment]
The behavior may have changed from our old Jekyll build process to the new Federalist build process, since it depends on the Jekyll builder's configuration, and what Markdown engine you use. It looks like [Federalist at least includes kramdown](https://github.com/18F/federalist/blob/master/Gemfile.lock), but I'm not sure what it uses by default to build sites.

(Also, the technical term is "ensmartening".)

**Comment by gemfarmer** [comment]
@coreycaitlin are you seeing issues with quotes in places unrelated to [the apostrophe change that you made in author.rb](https://github.com/18F/18f.gsa.gov/pull/1995/files#diff-b4a8e4fc2fca3de886471e0396ba04c4R58)? I'm _guessing_ that the issue there is that the liquid filter is running _after_ the markdown is rendered, so the unsmart punctuation in that file isn't getting markdownified _again_

**Comment by coreycaitlin** [comment]
@gemfarmer Yes — this might be easiest to demo over screenshare. Let's pick this up in our next pairing session!

**Comment by gemfarmer** [comment]
Agreed! Next pairing session it is!

**Comment by gemfarmer** [comment]
@mugizico [this might be useful](https://github.com/jekyll/jekyll-help/issues/56)
