### ISSUE TITLE
Add analytics tracking to homepage and intake calls to action

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2014]
As we work to measure how the site is doing, it would be great to be able to track how many people are clicking on this button and this email link:

![screen shot 2016-11-02 at 3 02 51 pm](https://cloud.githubusercontent.com/assets/1450354/19949170/7c82f8c6-a10d-11e6-807f-f1e8d1403488.png)

![screen shot 2016-11-02 at 3 02 59 pm](https://cloud.githubusercontent.com/assets/1450354/19949172/7f19e086-a10d-11e6-8e80-8f80cb49adcf.png)

## This is issue is done when:
- [x] We can get a baseline measurement of how many visitors are clicking each of those links

**Comment by toolness** [comment]
This is totally doable with the DAP tracking that's already being done on the site! 🎉 

To access the custom reports I've shared below, you'll need to apply for DAP access on #g-analytics on Slack if you haven't already.

[Here is a custom report showing the custom event types being tracked.](https://analytics.google.com/analytics/web/template?uid=Nyhj9N3wRLSGlJhoM5HhRg) Under the **Event Category** column, click on the **Outbound MailTo** item to drill-down and see all the specific email addresses that were clicked on. Right now it looks like there have been 10 clicks on inquiries18F@gsa.gov during the period from Oct 21 to Nov 20.

[Here is a custom report showing where visitors to `/tags/fec-gov` came from.](https://analytics.google.com/analytics/web/template?uid=J5u8uUqlRl6FIutT5wzkwA) The one at the top of the list is `18f.gsa.gov/` meaning the 18F site homepage. It looks like there have been 177 users who clicked on that button during the period from Oct 21 to Nov 20. (That said, there's a big warning at the top of the report that says "You are using a filtered view, which may cause your Users count to be inaccurate", so there might be a more accurate way to get this info.)

Anyways, I'm a relative newcomer to google analytics so I bet Tim Lowden and others know of much more efficient ways of getting at this info.

**Comment by elainekamlley** [comment]
Thanks @toolness! 

@coreycaitlin @gboone Are you able to see these reports?

**Comment by toolness** [comment]
So Corey and Elaine and I just video-conferenced and realized that Google Analytics asks a very confusing question when opening those shared reports, which is what tripped folks up:

> ![screen shot 2016-11-29 at 2 14 03 pm](https://cloud.githubusercontent.com/assets/124687/20724920/2826bf24-b63e-11e6-85ce-ab5a72341b86.png)

It's confusing because at 18F, we actually have access to *two* Google Analytics accounts: 18F's non-Premium account and [DAP](https://www.digitalgov.gov/services/dap/)'s premium government-wide account. The reports I made were for the latter (I could only make the Outbound Email one with DAP specifically, because only DAP tracks outbound emails).

Anyways, ultimately what that means is that you want to choose **GSA Agency Profile** under the view drop-down:

> ![screen shot 2016-11-29 at 2 17 25 pm](https://cloud.githubusercontent.com/assets/124687/20725049/a14284ba-b63e-11e6-92a8-409c275176e6.png)

Anyhow, if you want to learn how to create these reports yourself, I highly recommend Tim Lowden's DAP virtual training videos. They are long--over 2 hours each--but you can use YouTube's [playback speed](http://adrianroselli.com/2014/07/changing-youtube-playback-speed.html) UI to get through them faster if you want:

* [DAP 101 video](https://www.youtube.com/watch?v=CKMTK77PrJE)
* [DAP 201 video](https://www.youtube.com/watch?v=rPo3zFbhXnk)

Hope that helps!

**Comment by coreycaitlin** [comment]
Yay! Thanks for tracking this down @elainekamlley and @toolness 🎉 

We now have a baseline. In the last two weeks (since there's a holiday in there):

- About 45 users went to the FEC project page, mostly from the homepage
- 4 people clicked on the `inquiries18F@gsa.gov` mailto link

**Comment by gemfarmer** [comment]
🎉 thanks @elainekamlley and @toolness !!
