### ISSUE TITLE
Visual design for subnav: mobile

### ISSUE THREAD

**Issue by ericronne** [18F/18f.gsa.gov#2030]
Here's the mobile navigation, fleshed out to another layer (desktop design tracked in #1954).

Also, i'm experimenting with a black background, which is striking, and lends a little more elegance to the design.

### Check out the [Invision prototype](https://gsa.invisionapp.com/share/DM99AUBG9#/203657587_Mobile-Submenu-1)

Feel free to use the Invision commenting tool to record thoughts and questions.

![mobile-submenu-2](https://cloud.githubusercontent.com/assets/9259185/20119055/9119ee66-a5cc-11e6-8e3e-b1541a77e2b5.png)

@coreycaitlin @gboone @gemfarmer

**Comment by ericronne** [comment]
:Facepalm:
Looks like the WDS has a pattern for mobile subnav. Arguably not as "interesting" as the above, but if we want to apply the standards to this site wherever they may fit, something closer to this could work.....

![image](https://cloud.githubusercontent.com/assets/9259185/20177942/e91db496-a714-11e6-8fc8-7fe4b5f65924.png)

**Comment by gemfarmer** [comment]
@ericronne this looks like a good place to start. Should I start implementing?

**Comment by ericronne** [comment]
Sounds like a plan. Especially since i have little time to dedicate to this.

cc @austinhernandez 👋

**Comment by gemfarmer** [comment]
@ericronne @austinhernandez what are your thoughts on how we want to merge the subnav items with the top level mobile nav items?

<img width="300" alt="screen shot 2016-11-14 at 3 52 37 pm" src="https://cloud.githubusercontent.com/assets/4803473/20284363/6ae1dbea-aa82-11e6-822b-cc0a9d4f9699.png">

**Comment by gemfarmer** [comment]
To clarify:

Currently there is one "global nav" That has the top level routes:
  - /what-we-deliver/
  - /how-we-work/
  - /hire/
  - /join/
  - /blog/

This issue is proposing that we add a subnav to specific pages that help navigate to lower level routes within that top level route. In desktop displays, there is no interference, but in mobile, if we are trying to have the subnav/sidenav in a drawer, it might conflict with the global nav in style and function. How do we deal with that?
