### ISSUE TITLE
Investigate Twitter Card, OpenGraph anomalies

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#2059]
## Expected Behavior
When a post or page is shared on Facebook:
* The post's `image` should display alongside the `description` when shared.
* On twitter this produces a "card" ([example](https://twitter.com/18F/status/801449484148416513) when posted
* On Facebook, Slack, and other OpenGraph users, the details fill in while you are sharing the post.

## Actual Behavior
* OpenGraph shares do not expand at all
* Twitter cards don't expand, only get the link ([example](https://twitter.com/18F/status/801448100955127808))

## Steps to reproduce the behavior
- [ ] Share a post on a social network or use [Facebook's OpenGraph Debugger](https://developers.facebook.com/tools/debug/sharing/) and [Twitter's card debugger](https://cards-dev.twitter.com/validator)

These validators require logging in.

## This is issue is done when:
- [ ] validators show the information is properly formatted for sharing
- [x] Twitter cards should appear when posts are shared

**Comment by gemfarmer** [comment]
@gboone I am addressing this problem in #2065. It is definitely working in Federalist. It should work in Twitter, but it is hard to know for sure because the image path is being altered to `https://18f.gsa.gov/preview/18F/18f.gsa.gov` :( I vote that we see what happens when this is merged into master, and close this ticket if it is fixed then. Does that sound good to you, or is this more urgent than I am making it?
