### ISSUE TITLE
Create example styles page / template and pattern library

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2089]

**Comment by gemfarmer** [comment]
This issue is to create a page (or set of pages) that document how different styles, includes and layouts are used throughout the site. 

This has a few benefits:
- We would be demonstrating how layouts, templates, and styles exist within the _actual_ site environment
- Eliminate work of creating a autogenerating styleguide or Sketch styleguide
- Would exist as a guide for how to integrate USWDS and Brand that could help people port information from `18f pages`
- We could rely more heavily on the styleguide set up by WDS
- Would force us to reduce the number of layouts we rely on. 

cc @austinhernandez @coreycaitlin

**Comment by coreycaitlin** [comment]
This is successfully started, and ready to be maintained on an ongoing basis as we refine and add styles 🎉
