### ISSUE TITLE
Hero image for state & local project page

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2101]
We need a hero image for the state & local project page, which is focusing first on HHS work with California. This will go in the same layout as the [FEC project page](https://18f.gsa.gov/project/fec-gov/), so contrast isn't too much of an issue.

**Comment by austinhernandez** [comment]
here are 4 different variations on 2 concepts -  https://invis.io/3X9J87M4V#/210023057_State_-_Local_Headers

**Comment by coreycaitlin** [comment]
Let's go with photos here, since those nicely show the collaboration inherent in this work.

**Comment by austinhernandez** [comment]
the favorite photo chosen on invision is here to download and view. dimensions are 610 x 257px - https://invis.io/a/VHBK11PU7CFXQ 

i got the dimensions from the 18F sketch file, but the FEC hero (/assets/img/home/hero-fec.png) appears to be  2048 x 860px! idk if that's because it's vector or what, but please let me know if I should be making the files that big.
