### ISSUE TITLE
Search results include pages with empty titles

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#2109]
## Expected Behavior
A search results page [like this one](https://18f.gsa.gov/search/?q=testing) should only show results with page titles and navigable page paths.

## Actual Behavior
Search results contain some pages with no title, and no clickable link.

## Steps to reproduce the behavior
- [ ] Do a search, any will do [but here's an example](https://18f.gsa.gov/search/?q=testing) and look for results like `1. ` 

## This is issue is done when:
- [x] All results of a search are clickable links

**Comment by gemfarmer** [comment]
Ok, so after a bit more research, this appears to be caused by a few things
- files that weren't excluded in the build (contributing.md, for example) get indexed
- built redirect pages get built and are indexed. Adding `skip_index: true` to the frontmatter should prevent this, but several of the `redirect_from` pages don't have frontmatter.

**Comment by gemfarmer** [comment]
Appears that adding `skip_index: true` to dead pages works, the site just wasn't building properly.

Also, I am adding the [results UI script](https://github.com/18F/jekyll_pages_api_search#results-ui-and-search-engine-options) to the javacript include so that we can filter the results. This will have the added benefit of allowing us to redesign the blog search results UI.

**Comment by coreycaitlin** [comment]
I believe this is solved in [release 1.1.3](https://github.com/18F/18f.gsa.gov/releases/tag/1.1.3)
