### ISSUE TITLE
Add TTS Logo to 18F Site Footer

### ISSUE THREAD

**Issue by wslack** [18F/18f.gsa.gov#2155]
Looks like there is space for a mini TTS logo between the 18F and GSA logos at 18f.gsa.gov - wanted to ask if we should add it!

**Comment by coreycaitlin** [comment]
This is a great idea, but we should probably do this when we get an `About 18F` page up, so we can explain the relationship.

**Comment by coreycaitlin** [comment]
We explored including the TTS logo on an About page, but because the logo doesn't include the acronym, it is likely to add confusion rather than creating clarity. It's also a little unclear at small sizes, and there's some potential for confusion because it only depicts the continental U.S.

@gboone also noted that other parts of GSA (within the other services) don't self-identify as parts of those services.

I recommend we keep the logos in the footer to just GSA + 18F, but explain our affiliation with TTS on the About page (#2186). @gboone — does that sound like a good plan?

**Comment by gboone** [comment]
Agreed.
