### ISSUE TITLE
Tags: Style for URL vs project name

### ISSUE THREAD

**Issue by awfrancisco** [18F/18f.gsa.gov#2161]
## Expected Behavior
We should have a consistent tag style for projects.

## Actual Behavior
Some projects use the URL for the tag (pulse.cio.gov) while some use the project name (CALC). We should choose a consistent style and apply it across projects.

## Steps to reproduce the behavior
- https://18f.gsa.gov/tags/

## This is issue is done when:
- [ ] We decide on a style
- [ ] That style is applied to current tags
- [ ] That style is documented somewhere

**Comment by coreycaitlin** [comment]
[Related wiki page](https://github.com/18F/18f.gsa.gov/wiki/Project-names)

**Comment by coreycaitlin** [comment]
Current project tags include:

- agile bpa
- analytics.usa.gov
- c2
- calc
- cloud.gov
- code.gov
- college scorecard
- data act
- department of commerce
- department of labor
- digital acquisition accelerator
- discovery.gsa.gov
- environmental protection agency
- eregulations
- every kid in a park
- fbopen
- fec.gov --> federal election commission
- federal front door
- federalist
- foia
- health and human services
- micro-purchase platforms
- midas
- myusa
- national technical information service
- navy reserve
- open opportunities
- peace corps
- pulse.cio.gov
- u.s. geological survey
- uscis
- useiti
- vote.usa.gov
- web design standards

Overall, these tags seem pretty reasonable — in many cases, where we're using a URL, it's because the words in the URL would make less sense alone (i.e. `cloud`, `pulse`, `analytics`) and a full project name that isn't the URL would be much longer and potentially less recognizable. I do think we should change `fec.goc` to the full agency name, and noted that above. Feel free to edit this comment to make other recommendations!

**Comment by gemfarmer** [comment]
[Current tags list](https://github.com/18F/18f.gsa.gov/blob/master/tests/schema/tags.yml)
