### ISSUE TITLE
Content: eRegs project intro

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2189]
We need content for the project-tag landing page about this project.

## This is issue is done when:

- [x] Content is drafted
- [x] Content is reviewed and revised with outreach team
- [x] Content is reviewed by Jen E

**Comment by coreycaitlin** [comment]
[Draft goes here (limited access)](https://docs.google.com/document/d/1_Q5Efv1ZRm56jFa2GLCV8VqbFsu3-TCwxMYU9DOMb-A/edit))

**Comment by kategarklavs** [comment]
Howdy! Happy to take this on :)

**Comment by kategarklavs** [comment]
@coreycaitlin Howdy! Just finished up a draft intro — I'd love your feedback on it! (I'm worried that it might not be detailed enough, but I wanted to stay within the general length as established by the other few project intros I read.)

In any event, let me know what you're thinking &  I'll get to editing! 😎

**Comment by kategarklavs** [comment]
Quick update: Pinged Will Sullivan yesterday with some questions whose answers will help me develop the current draft a bit more; Will said he'd get back to me within 48 hours. In the meantime, I'll work on the C2 description. More news as I have it!

**Comment by kategarklavs** [comment]
Just did a quick review of this summary, and I think it's ready for Outreach review 

cc @coreycaitlin & @awfrancisco

**Comment by awfrancisco** [comment]
This is looking good. I think it properly gives credit to CFPB while still focusing on our work. I changed instances of `eRegs` to `eRegulations` since this will likely be the canonical source of info about the project and we should probably use the full name. 

I know we're keeping these informational, but it still felt like it should end with a call to action to get this platform for yourself. More so than CPS-type project pages. I think the new project page layout will address this and we don't need to add it in here, just registering my reaction.

**Comment by coreycaitlin** [comment]
I think this is great — I'll start up a branch for moving these all into markdown.

**Comment by kategarklavs** [comment]
Sent Jessie the draft for review.

**Comment by kategarklavs** [comment]
@jehlers reviewed this content with us on 2/3, and we made updates per her recommendations.

**Comment by kategarklavs** [comment]
@coreycaitlin Hey! Am I safe to close this one, or do you feel like the content needs one more review?

**Comment by coreycaitlin** [comment]
Let's close it out!
