### ISSUE TITLE
Markup/blog styleguide items

### ISSUE THREAD

**Issue by gemfarmer** [18F/18f.gsa.gov#2242]
It would be interesting to turn the styleguide into a list of HTML and/or liquid snippets that can be added to markup to enhance a page. The snippets could include documentation about how to use them and how to do so with accessibility concern in mind.

Running list is as follows:
General:
- [x] typography
- [x] font family
- [x] buttons
- [x] background colors
- [x] project cards 
- [ ] form elements
- [x] icon catalog
- [x] pattern: list of icons
- [x] sticky navigation
- [x] right-aligned page attribute list (as seen in project pages and Contact)

Blog:
- [x] blog preview cards
- [x] oEmbed
- [x] blog tags
- [x] blog preview layout
- [x] figure/figcaption
- [x] team photo
- [x] blockquotes
- [x] blog images

Full width:
- [x] full width banners
- [x] breadcrumb

Technical:
- [x] Feature of available plugins (filters and tags) that are used throughout the site, with a link to the more [in-depth documentation](https://github.com/18F/18f.gsa.gov/tree/master/_plugins)
- [x] Update in-depth documentation

cc @gboone @awfrancisco @elainekamlley

**Comment by coreycaitlin** [comment]
ooh I like this idea

**Comment by coreycaitlin** [comment]
Started this [here](https://github.com/18F/18f.gsa.gov/tree/master/examples), but the styleguide seems like a much better place for it

**Comment by gemfarmer** [comment]
Started a conversation about potential user needs on [slack](https://gsa-tts.slack.com/archives/beta-18f-site/p1488554360002607)

Also [Austin's sketch styleguide](https://projects.invisionapp.com/share/3X9J87M4V#/screens/209057303) for reference

**Comment by gemfarmer** [comment]
- Add code blocks that are the language or syntax that we would use in _actual_ implementation (html, liquid, etc.). For components in which liquid is the preferred implementation, show that, but also the html that it evaluates to.
- Expand the width of the component layout

**Comment by gemfarmer** [comment]
Primary things to focus on
- [ ] Start to add a `stylguide/core/` page to flesh out Austin's sketch guid **@elainekamlley** 
- [ ] Create a new layout and documentation structure/pattern **@gemfarmer**

**Comment by jenniferthibault** [comment]
Thanks so much @elainekamlley & @gemfarmer for all of your incredible work getting this up to speed so quickly, and for the opportunity to provide feedback. 

I tried to focus on tweaks that: 
1. clarified and corrected visual guidance on existing elements in order to make them most usable now
2. would make this guide feel consistent with other UI documentation 
3. keep the documentation open-ended to allow the guidance to grow

I definitely tried to draw a line between tweaks to make it correct & usable now, and enhancements that could be made to make things _better_ later. 

Here's what I'm thinking, roughly ordered by what feels most important. I'm glad to discuss any/all of this more, or pair with you as it's implemented. Thoughts welcome!


- [ ] **Bring back the persistent exposed side-nav on the left.** (using the style seen on the [About](https://18f.gsa.gov/about/) page)
  - One way to do this and keep the body content area maximized would be to use a full-page-width container, like we initially did in the [brand guide](https://pages.18f.gov/brand/color-palette/) (disclaimer, somewhat dated). In this instance, I think that page template better fits documentation patterns, so would be appropriate to be "unique" to the site, but fit the pattern that feels established for documentation sites, even like the [USWDS](https://standards.usa.gov/components/colors/)
  - To support the mental model of UI documentation guides established in the USWDS, break the style guide up in to multiple pages instead of one long page. Until we really need an intro page, the first page can open to "typography" and the header can be what it is now. (I'd expect that to evolve later on)
  - ![screen shot 2017-03-15 at 12 23 31 pm](https://cloud.githubusercontent.com/assets/11636908/23959003/46dda376-097a-11e7-9cfa-4cdd7c7c0dbb.png)

- [ ] **Change `styleguide` to `style guide` in all instances**
  - Two words, crazy, right?
 
- [ ] **To support the mental model established in the USWDS, use their pattern for code & documentation elements**
  - Under the example elements, position “code” first but closed, then “documentation” second but expanded.

- [ ] **Restructure "typography" section to be unified and comprehensive**
  - To keep the topics that are related together under one umbrella, `Font family` can be merged into `Typography`, as long as we create section titles for the other components as well, such as `Typesetting` for hierarchy, and `Links` for link styles. (Copy open to suggestions!)
  - ![screen shot 2017-03-15 at 12 35 50 pm](https://cloud.githubusercontent.com/assets/11636908/23959592/f688820e-097b-11e7-988b-3cbd192aab5d.png)

- [ ] **Adjust layout of color swatches so that primary colors and their corresponding hover colors are paired**
  - To make clear that  `$color-medium-hover` and `$color-bright-hover` are not primary palette colors on their own. (screenshot below)
- [ ] **Add color variables and swatches for white & black**
  - So that front end users can know what the variable names are, and so that visual designers can know what the hex values are
  - Not crucial, but ideally the `$color-X` part of the phrase would be bold weight, and the hex code would be regular weight, as styled in the screenshots below
  - ![screen shot 2017-03-15 at 12 52 52 pm](https://cloud.githubusercontent.com/assets/11636908/23960429/57bfc4b8-097e-11e7-9712-7e851a0ae6b2.png)

- [ ] **Adjust background card info to use variables**
  - Instead of hex codes, identify the color with the `$color-` variable
  - Use `Text:` instead of `Font:` for clarity about what element you are specifying the color for
  - If it makes sense in the new page layout with menu, try 2x2 grid instead of 4x1? But not a necessary change if the 4x1 keeps working in the new format
  - ![screen shot 2017-03-15 at 12 57 56 pm](https://cloud.githubusercontent.com/assets/11636908/23960691/0b2a94ba-097f-11e7-824f-4f89b15080ab.png)

- [ ] **Add sub-heads to button section to clarify use case**
  - ![screen shot 2017-03-15 at 1 02 41 pm](https://cloud.githubusercontent.com/assets/11636908/23960934/bb7bbefc-097f-11e7-9a0e-d92906b64293.png)

**Comment by gemfarmer** [comment]
Thank you so much for the feedback, @jenniferthibault !

I really don't see much of an objection to any of those points. @elainekamlley and I can keep working on this and get back to you with a v2!

**Comment by gemfarmer** [comment]
Done as of #2365
