### ISSUE TITLE
Project pages: Final go-ahead and reviews

### ISSUE THREAD

**Issue by coreycaitlin** [18F/18f.gsa.gov#2283]
- [x] [CALC](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/calc/) - #2201 
- [x] [Ready-2-Serve](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/navy-ready-2-serve/) - #2248 
- [x] [C2](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/c2/) - #2202 
- [x] [Agile BPA](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/agile-bpa/) - #2250 
- [x] [Federalist](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/federalist/) - #2204 
- [x] [DATA Act](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/treasury-data-act/) - #2106 
- [x] [eRegs](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/eregulations/) - #2189 
- [x] [myUSCIS](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/dhs-myuscis/) - #2200

**Comment by awfrancisco** [comment]
@coreycaitlin My notes going through the pages are below. Couldn't figure out the eRegs and USCIS links, but can update if you have them handy. Also, does it matter that at this stage the pages have different URL structures (/what-we-deliver vs /project)? Or will that be solved on merge? 

CALC

- add link to github https://github.com/18F/calc

Ready-2-Serve

- add link to github https://github.com/18F/r2s
- recommend moving quote to bottom of metadata, but open to other thoughts

C2

- github link style of 18F/reponame looks pretty confusing. Not sure how to fix, but we should revisit in next sprint
- Quote needs attribution otherwise it looks like we are saying it about ourselves. Might even want to take out. Kind of glib/non professional. 

Agile BPA

- why is the learn more button here and not on some other pages?
- We should list all agencies on this page if possible https://pages.18f.gov/ads-bpa/
- list all the github repos? https://github.com/18F?utf8=%E2%9C%93&q=bpa&type=&language=
- add link to subscribe to acqstack email list? (or add to next sprint)

Federalist

- list agencies in alphabetical order
- repos?

DATA Act

- repos?
- Style question: we abbreviate this in the header but spell out agile bpa. Which should we use?

eRegs

- 404s. Link?

USCIS

- 404s. Link?

**Comment by coreycaitlin** [comment]
Notes:

- Removing quotes without attribution, because I agree

Next sprint / further discussion:

- GH repo name link text?
- link to acqstack email list?
- improved "learn more" handling

Formerly broken links:

- [eRegs](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/eregulations/)
- [myUSCIS](https://federalist.18f.gov/preview/18F/18f.gsa.gov/dev/what-we-deliver/dhs-myuscis/)

**Comment by acolter** [comment]
Regarding images for Ready-2-Serve, Tom suggested https://drive.google.com/file/d/0B1ebyFpRd3jVZ0ZEOFplS0FObU0/view if you would prefer to use that, @austinhernandez

**Comment by awfrancisco** [comment]
eRegs and myUSCIS look good from me.
