### ISSUE TITLE
18f.gov Styleguide is down

### ISSUE THREAD

**Issue by joe-watkins** [18F/18f.gsa.gov#2333]
## Expected Behavior
Visiting https://pages.18f.gov will work.

## Actual Behavior
Visiting https://pages.18f.gov results in "The request could not be satisfied." error.

## Steps to reproduce the behavior
- Visit https://pages.18f.gov in any web browser

## This is issue is done when:
- https://pages.18f.gov works :)

**Comment by gboone** [comment]
Thanks, @joe-watkins This is related to problems with Amazon S3. Unfortunately we will have to wait for S3 to get healthy again before pages.18f.gov is again available.

Closing this issue since it is not related to 18f.gsa.gov. If you'd like to reopen with [18F/pages](https://github.com/18f/pages), you could but my understanding is that it's not something we have a ton of control over at the moment.
