### ISSUE TITLE
Research: Partners needs from the 18f.gsa.gov contact page

### ISSUE THREAD

**Issue by elainekamlley** [18F/18f.gsa.gov#2490]
Research with agency partners what they need/want from https://18f.gsa.gov/contact/. The current plan is to bring the Partnership Playbook (linked on that page) into the 18F site from 18F Pages. We need some research to identify additional content or functionality for that page. 

## This issue is done when:

- [x] [Research plan is created](https://docs.google.com/document/d/19gSpx0JUk5W-RnTkCpDBb6F3W_1ClTUmSuQb1XjFq-A/edit?usp=sharing)
- [x] Research with partners
- [x] [Summary of findings is captured and distributed ](https://docs.google.com/document/d/1UHxSQH82-mJKQTrJNLh-VQd2SwzLRZuKZsSmWACVjXM/edit#)
- [x] Create new design
- [ ] Publish new design

**Comment by Dahianna** [comment]
## Recommendations TLDR

- Redesign the contact page to have the emails in the front of the page and not on the sidebar.
- Discuss if the paragraphs in the contact page are necessary or are they better suited for other areas of the site such as “How we work”
- Revisit the possibility of creating a contact form.
- Include some information on 18F’s locations
- Remove email us button from the contact page.
- Similar to the Code of America page we can move these resources to the sidebar for related pages. 
- The partnership principals and funding information should live in the “How we work” page

**Comment by Dahianna** [comment]
Mockup
![contact page mock-up](https://user-images.githubusercontent.com/22921144/46978156-22ac6880-d09c-11e8-905e-2de39f2406e2.jpg)

**Comment by awfrancisco** [comment]
[Issue for writing lab](https://docs.google.com/document/d/1rzhUsqCVwpsONhP1gj8nuTOpVShebc4ynrIuiRa5X4o/edit)

**Comment by Dahianna** [comment]
@juliaklindpaintner Thank you for helping us out with the new design of the contact page. Above you can find a mockup I created of the new design based on the research findings. (I am not a designer so the images are a bit distorted) Feel free to use the mockup as you please and make recommendations of your own. If you have any questions feel free to reach out.

**Comment by jenniferthibault** [comment]
@juliaklindpaintner I'd love for you to give our new 18F site design files a test drive 💪 🚗 🏁 

We have a [sketch file of page designs](https://drive.google.com/open?id=1z_ZfIi_GzwvHOZHGhWCf5EKjMqo_KCdB) which is powered by a [sketch library file](https://drive.google.com/open?id=1vMHxBnqARMMtZKDVNkg5vmkGjMdHR6Gl)

Open the `18F-site-pages` file first and there is an `Instructions` page set as page 1 in the layer list. If you need any quick tutorials on Sketch symbols & libraries, try out our brand new [Visual Design Practices](https://docs.google.com/document/d/1VRD8HgJunq_sQQim6t7I8bALdTLF7KzC15tR8lOYv7k/edit#) guide or come find us in #visual-design or #sketch on slack. Feedback on all of the above welcome.

When you're done, please make sure to re-upload the files back onto Google drive in the [18F Site Design folder](https://drive.google.com/drive/u/0/folders/0B0ppzHnivtsDcDc0VEQxNlhWdWs) so that the rest of the team has access to the most complete and up-to-date set of files. 

⭐️ Bonus points if you update the contact page image so that it's not my face anymore. It's lonnnnng overdue (as you can tell by how short my hair is there, and how long it is now 😉 )

**Comment by juliaklindpaintner** [comment]
Thanks @Dahianna and @jenniferthibault! Two quick questions: 
1. Since I haven't worked on the site before, just so I know: If I put together the proposed mock-up in Sketch, will that be sufficient for whoever is implementing on the site? 

2. The current mock-up doesn't show the newsletter sign-up; is that intentional? Seems like the only place on the site it exists...

**Comment by Dahianna** [comment]
@juliaklindpaintner Yes, the Sketch files are sufficient. We'll ask a developer to create a pull request to add it to the site.  When I created the mockup we had a hold on the external newsletter, but we'll start publishing it again soon. So we'll need the sign up box to the contact page as well.

**Comment by juliaklindpaintner** [comment]
@jenniferthibault and @Dahianna Here's a first draft for some feedback before I work on the mobile layout. I wasn't sure if the content was fully finalized/vetted, so I made a few suggestions. Everything is based on the mock-up, research feedback, and current https://18f.gsa.gov/contact/.

<img width="577" alt="18f contact page_v1" src="https://user-images.githubusercontent.com/42982184/50788654-ff9ee880-1287-11e9-9ed8-fb9b75b0ec6c.png">



Notes: 
- I took out "Have a project in mind" and made "Want to see if 18F can help your agency" the headline of the first contact line so that it's a simpler Q & A format for all of them. Happy to change back if you prefer.
- Created 2 separate sidebar sections: "Learn more about 18F" links to the items that are at the bottom of the current contact page; "Follow 18F" links to our social media/github/rss.
- Added social icons
- Reconstructed the existing newsletter sign-up—but this wouldn't need to be recoded, could just remain from current version.

**Comment by Dahianna** [comment]
This is great! @eddietejeda and @awfrancisco what do you think?

**Comment by awfrancisco** [comment]
Looks great!

**Comment by Dahianna** [comment]
@juliaklindpaintner I talked to @eddietejeda and he likes the new design as well. Thank you for your awesome job!

**Comment by juliaklindpaintner** [comment]
Great! I'll do the mobile tomorrow and get you the files asap!

**Comment by juliaklindpaintner** [comment]
@Dahianna All set! The Sketch file is here: 
https://drive.google.com/open?id=1nh6ukNN9_iHogWIFnVw3E_n9c64Bo93i
For vertical spacing, best to just use the default spacing associated with semantic styles.

Mobile: 
![contact - mobile](https://user-images.githubusercontent.com/42982184/50845696-7ea12900-133b-11e9-85ed-8728a1041ed5.png)

Web: 
![contact - large](https://user-images.githubusercontent.com/42982184/50845712-88c32780-133b-11e9-9fa9-42dd24c24208.png)

@jenniferthibault Updated Sketch pages and library files are in the Drive folder.

Let me know if you need anything else!

**Comment by Dahianna** [comment]
Thank you so much!!

**Comment by juliaklindpaintner** [comment]
My pleasure! Let me know if there are any other projects you need help with!

**Comment by Dahianna** [comment]
Design is ready and being implemented in #2958
