### ISSUE TITLE
Accessibility contrast bug on "our work" page with Chrome

### ISSUE THREAD

**Issue by LindsayYoung** [18F/18f.gsa.gov#3796]
## Expected Behavior
Contrasting colors on the "get in touch" button at this url: https://18f.gsa.gov/our-work/

## Actual Behavior
This is my screen shot using chrome:
<img width="1213" alt="Screenshot 2024-01-08 at 3 14 40 PM" src="https://github.com/18F/18f.gsa.gov/assets/4406333/9881718d-8b7c-4289-8d27-43cbe9c0abec">

## Steps to reproduce the behavior
I only get this issue with Chrome, it looks correct in Safari. 
I tried clearing my cache and re-launching Chrome, but the issue persists for me.  I don't see any errors in the inspector on page load. 
It is possible it's just something weird locally for me, feel free to close the issue if you can't reproduce it. I wanted to file an issue just in case this is also happening to others.

## This issue is done when
- [ ] Contrasting colors load for chrome users

Thank you!!

**Comment by dluetger** [comment]
I can certainly look, but offhand to we know if this is a Design System issue or local only to this page? And if so, should we prioritize a quick-local fix first?

**Comment by dluetger** [comment]
`.usa-section--dark a:visited {
    color: #dfe1e2;
}`

Thinking aloud as I investigate. The link is classed like it's on a dark background (it doesn't seem to know it's on a light button); so that's a thing. I'll look into how widespread that is or if it just needs an additional class

**Comment by dluetger** [comment]
It also isn't a button at all, at least in code, and this seems like one of those semantic edge cases

**Comment by dluetger** [comment]
Scratch that, it is a `usa-button` but is still getting the visiting link style applied like I said two comments up. I also replicated this in Safari

**Comment by dluetger** [comment]
Same issue also happens on the [homepage](https://18f.gsa.gov/) in the "What 18F can do" section, so I suspect any buttons on dark backgrounds would see this effect

**Comment by dluetger** [comment]
So for this site, it seems we implemented an 18F specific button class, `an18f-button--accent`, that has slightly different rules from `usa-button`. `an18f-button--accent` seems to be used exclusively for these dark background sections and has the light blue background color. It seems, though, for _both_ button styles, the intent is for it to _not_ change color at all once visited. There seems to be a cascade error for the 18F one though and it's getting the style of any visited link on a dark background instead of the intended, unchanged, color.
