### ISSUE TITLE
Migrate styles

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3848]
One of the things I'm noticing is that the link to the styles CSS is the only broken link in the site right now:

```
Check HTML Links
  📖 Found 1051 files containing
    🔗 46998 internal links
  👀 Checking...
  ❌ Found 1 missing reference targets (used by 957 links) while checking 1051 files:
    1. missing reference target _site/assets/css/styles.css
      from _site/2014/03/12/coming-soon/index.html:60:8 via href="/assets/css/styles.css"
      from _site/2014/03/19/hello-world-we-are-18f/index.html:60:8 via href="/assets/css/styles.css"
      from _site/2014/03/21/29-minutes/index.html:60:8 via href="/assets/css/styles.css"
      ... 954 more references to this target
```

```[tasklist]
### Acceptance criteria
- [x] Styles are correct, and showing the equivalent of what we see on 18f.gsa.gov (prod)
```

**Comment by jasnakai** [comment]
Consolidted the styles so that they visually match the live 18F website. Moved the relevant files from `_sass` to the `assets/common/styles` folder. Deleted the duplicate/unnecessary files and the `_sass` folder. Removed references to the `_sass` folder.
The CSS could use a cleanup since the styles from two sites were combined. I will do what I can but not get caught up on it.
Branch name: jn/fix-styles-link
