### ISSUE TITLE
Migrate image tags

### ISSUE THREAD

**Issue by beechnut** [18F/18f.gsa.gov#3855]
Images are currently referenced mostly through `<img>` tags, but we should convert them to using `image` / `image_with_class` shortcodes, in keeping with 18F/guides convention.

```[tasklist]
### Acceptance criteria
- [ ] There are no raw image tags `<img...` in any layouts or partials
```

**Comment by beechnut** [comment]
@SSPJ If you finish this and want more, #3858 is fairly related to this one.

**Comment by SSPJ** [comment]
@beechnut , @cantsin , and @bpdesigns I've opened https://github.com/18F/18f.gsa.gov/pull/3863 for this.

There's about 100 left to do. (They seemed to make more as I went. 😅 ) Many of them are easy, but a few have conditional logic that I'm not sure how to interpolate. Since I'm staffed to a new project on Monday, I'll let it to the three of you to decide where to take this ticket and pull request.

**Comment by cantsin** [comment]
Thanks! I think we can find someone else to pick up where this left off.

**Comment by beepdotgov** [comment]
Just a small scope question: there are a fair few raw `<img>` elements inside posts. Should those be converted over to shortcodes as well, or should I just be migrating the ones inside templates/partials?

Thank you!

**Comment by SSPJ** [comment]
@beepdotgov , if you are working from https://github.com/18F/18f.gsa.gov/pull/3863 I've already done a fair number of the `img` tags in the posts, although I don't know whether I was supposed to--I just assumed we should use the template syntax everywhere--so I appreciate you posing the question.

@beechnut left a review comment about the CSS that is worth keeping in mind if you are doing the `img` tags in the posts. Some of the old images have `width` (or other) attributes which I converted to CSS classes because they don't map cleanly to USWDS utility classes. Ideally, if you had time or motivation, you could swap out that bandaid CSS with USWDS classes and do a visual inspection to make sure they still look "right".

**Comment by beechnut** [comment]
@beepdotgov The goal is to replace all the image tags with the shortcodes, to align with the practice in 18F/guides. Feel free to do it in several passes — there's a lot of content to be replaced.

**Comment by beepdotgov** [comment]
@SSPJ @beechnut Hey, thanks to both of you -- this is just the direction I needed. Really appreciate it!

**Comment by beechnut** [comment]
@beepdotgov Based on our conversation, I'm going to revoke my last comment — this ticket is only to set up shortcodes in layouts and partials. We'll do blog post images post-migration in #3864.

**Comment by beepdotgov** [comment]
@beechnut Today's chat was _massively_ helpful. Thanks so much for talking through everything!

Working on getting the latest into my workspace now, and then I'll finish up the shortcode migration in the layouts/partials.

**Comment by beepdotgov** [comment]
Okay! Per this morning's chat, I:

- Pulled the full paths into our data files (https://github.com/18F/18f.gsa.gov/pull/3863/commits/03b653e661426eaf06a5aacefd870d97468152a1)
  - (Nice side effect of making this change? This eliminated the need to bother with string interpolation in the new shortcodes, so we could skip the `{% assign %}` step!)
- Migrated the remaining include/template `<img/>` elements over to use the shortcodes. (https://github.com/18F/18f.gsa.gov/pull/3863/commits/27f1973a033f10ed3749502667d660a879a9e274)

@beechnut Would it be helpful if I took a look at the open notes on the #3863 PR?

**Comment by beepdotgov** [comment]
Done, @beechnut! Left a question for you on one, and left another one open for review; everything else has been closed out.

Thanks again for all your help today!
