### ISSUE TITLE
Consider allowing for comments

### ISSUE THREAD

**Issue by gboone** [18F/18f.gsa.gov#488]
I'm conflicted on the value of comments in general, but there are ways to integrate them with a static site. Most recently I saw [this one](http://posativ.org/isso/). Not saying that's the one we should go with, I am saying if I don't write this down I'll forget about it.

**Comment by elainekamlley** [comment]
I'm not sure about this either, not because I don't want people commenting but mostly on what our strategy will be for them. 
- What comments do we respond to or not respond to? 
- Who's role/responsibility will it be to respond? 
- How to address agitators or "trolls"?

**Comment by esgoodman** [comment]
I agree with @elainekamlley. Another option is to solicit comments but respond to them in longer blog posts -- kind of an advice columnist approach, where a few comments get long, thoughtful responses but it's understood that not every comment will get featured.

**Comment by kategarklavs** [comment]
+1 to @elainekamlley and @esgoodman's input. The advice column approach seems especially useful here – this way, readers feel that their input is being acknowledged, and we'll be able to offer more comprehensive responses than we would were we just responding via comments. 

Soliciting reader feedback (especially re: upcoming post ideas) is something I'd love to see more of – it's a great way to make sure we're meeting readers' needs.

**Comment by anthonygarvan** [comment]
Hey guys, I see this issue is closed as "Finished", but I don't see a place to put comments anywhere on your blog posts. What is the status here? Almost every other blog has a place for you to put comments, I see it as an easy and accessible way to respond to the article, and I enjoy reading other peoples comments as well. Even if nobody comments, having the comments box just says "we are an organization that invites feedback", which you clearly are, but not everybody knows how to open a git issue ;). 

This is a simple thing to set up in Jekyll (see [here](https://help.disqus.com/customer/portal/articles/472138-jekyll-installation-instructions)) Let me know if you want me to get it set up and issue a PR. 

To @elainekamlley's  points, 
- What comments do we respond to or not respond to?
--> most people who comment will just be responding to the article and won't expect responses. You guys don't write really incendiary stuff, and even mainstream new articles that reach millions of eyes often get only a handful of comments. In the worst case scenario, not responding to comments at all is still better than not allowing people to make comments.

- Who's role/responsibility will it be to respond?
--> Obviously don't know about your internal processes, but again I think you are overestimating the number of comments you will get and how complex they will be to respond to. I would imagine that if you write a post that gets a lot of discussion, that is a great sign and stakeholders within 18F will be eager to respond. 

- How to address agitators or "trolls"?
--> This is basically handled by disqus, they filter out spam and let you moderate. In my experience, it is very clear what comments to allow and which to disallow. 

So, in general the things you bring up are not particular to 18F but common across all blogs, and are part of the work and fun of having a blog. So, there's my pitch for comments on blog posts, let me know what you think and if you want some help implementing them on the technical side.

**Comment by konklone** [comment]
I think we decided it wasn't worth the time or energy, though of course we could always reconsider that.

I personally am unconvinced the value proposition of receiving and hosting comments is worth it for 18f.gsa.gov, and instead have gotten a lot of value out of engaging with readers and their responses on Twitter, Hacker News, Reddit, and other assorted services where discussion takes place.

> This is a simple thing to set up in Jekyll (see here) Let me know if you want me to get it set up and issue a PR.

Relying on a third party for user authentication, integrating their code onto our site, and storing user-submitted comments there is a non-trivial decision that affects the privacy, security, and performance properties of our website.

**Comment by anthonygarvan** [comment]
I can see how integrating a third party tool for user authentication could be a mess, but there is currently no clear invitation to give feedback via social media either. If comments are too complex for some reason, how about twitter / facebook share buttons? Almost every other blog / news outlet has these things, it just seems like an omission not to have anything on posts that encourages discussion. 

If you want to encourage people to discuss by your posts on twitter / reddit, you should include the buttons.
