### ISSUE TITLE
Policy and content strategy for microsites, guides and other content outside of 18f.gsa.gov

### ISSUE THREAD

**Issue by gbinal** [18F/18f.gsa.gov#493]
There are a [range of 18F standalone microsites](https://github.com/18F/analytics/blob/master/status.md), such as:  
* [18F Open Source Program](http://18f.github.io/open-source-program/)
* [FBOpen API docs](http://18f.github.io/fbopen/)
* [18F Consulting](http://18f.github.io/consulting/)
* [18F /Developer Program](http://18f.github.io/API-All-the-X/)
* [API Usability Testing Program](http://18f.github.io/API-Usability-Testing/)

At some level, those may make sense to transition to being a section of 18f.gsa.gov.  The outreach team has said that it is creating a process by which team members can suggest new (non-blog) content for 18f.gsa.gov.  I'd suggest that that process factor in the issue of when/how to integrate standing microsites.  

cc @blacktm, @gboone, @elainekamlley, @meiqimichelle

**Comment by meiqimichelle** [comment]
The challenge here is that the **content** in those sites may get transitioned up to 18f.gsa.gov, but it may not make sense for the entire **site** to move over _en masse_. Any new content for 18f.gsa.gov must reflect the audiences it is trying to reach and its overall information architecture. That being said, I believe there is place for almost all of the content listed here because finding a home for these sorts of content was revealed as a need when the 18f.gsa.gov team did user interviews, and so the site design is reflecting this.

So, to summarize for discussion here: I don't think the intent was to ever provide a process by which an entire microsite just gets stamped "good to go, you now get a sub-page on 18f.gsa.gov," but rather that there is a process for discussing and deciding how best to support and distribute content appropriately.

Also, we will continue the discussion here and other places on how best to keep everyone in the loop on progress on the 18f.gsa.gov site, and also how best to document decisions, etc, so the 18F team can contribute in constructive ways. Given the part-time nature of the team, the discussion will likely be slower than others would prefer, but it is the best we can do ;)

**Comment by meiqimichelle** [comment]
To be a little less jargony: the very short of it is that there is no way that we can just keep adding subsites such as 18f.gsa.gov/some-thing-here without any overarching structure. We won't be able to provide a navigation to all these places. We simply must bucket them into content types, and provide those types in a usable way.

The task that the 18f.gsa.gov team has taken on is spending the brain power on what those buckets should be, and how to organize content in a way that meets our audience's needs. It might be in the future that there is an easy, like, 18f.gsa.gov/guidelines/your-guideline-here and we can have a simple process for 'graduating' that type of content. It is this structured framework that we're working towards.
