### ISSUE TITLE
Add share buttons to blog posts.

### ISSUE THREAD

**Issue by melodykramer** [18F/18f.gsa.gov#529]
Opening a discussion to talk about whether we could put social buttons on blog posts. 

One thing to think about: buttons from the social networks themselves contain tracking information that goes back to them. (i.e. the Follow button from Twitter) After we determine whether share buttons are a good idea, we would also need to think about whether we'd want to use their buttons or make our own. I'm not sure if the gov't has guidelines for this.

**Comment by konklone** [comment]
Do you have any analytics you can share that point to the effect of using share buttons?

Third party service dependencies are something [talked](https://github.com/18F/18f.gsa.gov/pull/399) about [extensively](https://github.com/18F/18f.gsa.gov/pull/474). We also inline assets (rather than using content CDNs for e.g. jQuery), don't hotlink to third party images, and use YouTube's cookie-free version of their embeds. Privacy leakage to third parties is one of the least widely understood (and thus most broadly exploitative) areas of the web.

Share buttons are also used extensively in government, so there's certainly precedent, and there are [official OMB guidelines](http://www.whitehouse.gov/sites/default/files/omb/assets/memoranda_2010/m10-23.pdf) (which are in the process of being updated).

 I'm definitely open to the discussion and hearing that they're worth it. I have, personally, been skeptical of how much sharing they drive, even after reading [an Upworthy friend's 2012 defense of their efficacy](http://blog.upworthy.com/post/25921477695/actually-social-media-buttons-work-really-well) -- and, to the extent they may drive some sharing, whether cookie-cutter share tweets drive actual eyeballs.

**Comment by adelevie** [comment]
Do Twitter's [Web Intents](https://dev.twitter.com/web/intents) pose any privacy issues?

**Comment by konklone** [comment]
I'm not sure, but if they require using a `<script>` tag that linked to a Twitter-controlled domain, then it'd pose the same basic privacy issue as any other dynamic integration.

**Comment by gboone** [comment]
It's definitely possible to make share buttons without embedding anything, at least for Twitter it's just a link with URL parameters and Facebook will automatically use the open graph tags we already have. 

Getting the little share counter is a different story. Those are typically done with `iframe`s. It could _probably_ be done without third party embeds, not sure if it'd be worth the work, though. I share @konklone's general skepticism and am also willing to be persuaded by clickthrough data.

**Comment by melodykramer** [comment]
This is what made us hesitant to use the native share buttons on NPR's site: http://www.wsj.com/articles/SB10001424052748704281504576329441432995616

@konklone I've always seen it as more of a way to prime people to share rather than a means to share. But it largely depends on the site and how the share buttons are constructed. Buzzfeed's share buttons drive quite a bit of their traffic, particularly for Pinterest -- but they designed their share buttons to be really, really obvious and the language near them is designed to drive shares. We found that the buttons themselves didn't drive traffic -- but having them on the page caused shares to go up.

**Comment by melodykramer** [comment]
@konklone @gboone @adelevie Check out the shortened URL on these posts: http://www.nytimes.com/interactive/projects/cp/oscars-2015/show -- I don't think we need the share buttons themselves. But providing people with a shortened URL next to the word share could incentivize people to share. (And keeps the same shortened URL across sites, which is good for analytics.)
