### ISSUE TITLE
site needs typographically correct punctuation

### ISSUE THREAD

**Issue by jpyuda** [18F/18f.gsa.gov#744]
Right now, we have a bunch of incorrect punctuation like ' and " instead of “”‘’. Getting this right will both [help with legibility of the page](http://alistapart.com/article/typography) and will likely help us when recruiting designers (attention to detail matters, after all.)

Luckily, we can do this easily in the Jekyll configuration: https://github.com/blog/706-jekyll-puts-on-smartypants

**Comment by konklone** [comment]
:+1: if we can do it dynamically at render-time.

**Comment by gboone** [comment]
I think [since we use redcarpet we already have this](https://github.com/vmg/redcarpet/blob/v2.2.2/README.markdown#and-its-like-really-simple-to-use). The typography of quotation marks on [this recent blog post](https://18f.gsa.gov/2015/06/24/thomas-vander-wal-event/) and [this interior page](https://18f.gsa.gov/consulting/) appear to be "correct," anyway.
